version: '3.8'

services:
  php:
    build:
      context: .docker/php
    volumes:
      - .:/var/www/html
    networks:
      - lab1-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lab1-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab1
      MYSQL_USER: lab1
      MYSQL_PASSWORD: secret
    volumes:
      - lab1-mysql-data:/var/lib/mysql
    networks:
      - lab1-network
    ports:
      - "3306:3306"

volumes:
  lab1-mysql-data:

networks:
  lab1-network:
    driver: bridge
